drm/modes: add non-OF stub for of_get_drm_display_mode
If CONFIG_OF is disabled, of_get_drm_display_mode is not compiled in,
and drivers using it fail to build:

  ld: drivers/gpu/drm/imx/parallel-display.o: in function `imx_pd_connector_get_modes':
  parallel-display.c:(.text+0x8d): undefined reference to `of_get_drm_display_mode'

Add an inline stub so they can be build-tested with non-OF
configurations.

Issue: #MCOM03SW-2472
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Reviewed-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Acked-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
(cherry picked from commit 82581fcf070b68a91fb3a3ade08d9a76380a4789)
Change-Id: I691acc05f20e8e6b120ba97b1c2bb257785eb9e1