pinctrl: dwapb: Add GPIOLIB_IRQCHIP select
Without GPIOLIB_IRQCHIP irq field of struct gpio_chip is not declared,
and the build fails with the error:

  drivers/pinctrl/gpio-dwapb-pinctrl.c: In function 'dwapb_do_irq':
  drivers/pinctrl/gpio-dwapb-pinctrl.c:326:51: error: 'struct gpio_chip' has no member named 'irq'
                   int gpio_irq = irq_find_mapping(gc->irq.domain, hwirq);
                                                     ^~
  drivers/pinctrl/gpio-dwapb-pinctrl.c: In function 'dwapb_configure_irqs':

The error occurred due to the disabling of the unsued
GPIO_PCA953X/GPIO_PCA953X_IRQ in ECAM03, which selected GPIOLIB_IRQCHIP.

Ported from [1].

[1] https://gerrit.elvees.com/c/ipcam/linux/+/69687

Issue: #MCOM03SW-4344
Change-Id: I8f0b6146977c5a4cb0c758d904f94ca47e38da03
Signed-off-by: Maksim Tarelov <mtarelov@elvees.com>
(cherry picked from commit 0890335ed4f5ceae915fd08945e72fe1904e4a26)