arm64: dts: elvees: mcom03bub-fct: Disable I2C4
This commit fixes error:
   ERROR: mcom03_sip_wdt_ping: WDT Service failed to send msg, err = -60

The qlic driver probe procedure resets QLIC0 that leads to disabling
interrupts that have already been setup by firmware running on RISC0.
This in turn leads to timeout for WDT0 ping request when tl services
are enabled. As I2C4 is not used in functional testing we can
exclude mcom03-i2c4.dtsi from mcom03-bub-r1.3.0-fct.dts.

Issue: #MCOM03SW-2073
Change-Id: I4ad4639fbba22d10de3de58064462e3fee634ae4
Signed-off-by: Mikhail Konovalov <mkonovalov@elvees.com>
(cherry picked from commit a280ad3d6e4a830ba43b275c35db2091bba31771)