PCI: dwc: mcom03: Fix compilation with some gcc
This fixes gcc compilation error with message:
CC      drivers/pci/controller/dwc/pcie-mcom03.o
drivers/pci/controller/dwc/pcie-mcom03.c: In function 'mcom03_pcie_remove':
drivers/pci/controller/dwc/pcie-mcom03.c:696:2: error: label at end of compound statement
  696 |  default:
      |  ^~~~~~~

Change-Id: Iadff98eac8803d65592131942e5f571ea2e80506
Signed-off-by: Ilya Popov <ipopov@elvees.com>
(cherry picked from commit abaa42de4ec198255b1c9966b8cc7d534d37592e)